#!/usr/bin/env bash
# Bootstrap user-space rpmbuild + createrepo_c (no sudo).
# Downloads RPMs with dnf and extracts binaries/libs under TOOL_ROOT.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TOOL_ROOT="${NOVA_UPDATE_TEST_TOOLS:-${ROOT}/build/work/update-test/host-tools}"
CACHE="${TOOL_ROOT}/cache"
EXTRACT="${TOOL_ROOT}/extract"

mkdir -p "${CACHE}" "${EXTRACT}"

need_cmds=(dnf rpm2cpio cpio)
for c in "${need_cmds[@]}"; do
  command -v "${c}" >/dev/null || { echo "ERROR: missing ${c}" >&2; exit 1; }
done

PKGS=(
  rpm-build
  rpm-build-libs
  rpm-sign-libs
  createrepo_c
  createrepo_c-libs
  drpm
  ima-evm-utils-libs
  libfsverity
)

echo "==> Bootstrapping update-test tools into ${TOOL_ROOT}"

have_all=1
for p in "${PKGS[@]}"; do
  if ! compgen -G "${CACHE}/${p}-*.x86_64.rpm" >/dev/null; then
    have_all=0
    break
  fi
done

if [[ "${have_all}" -eq 1 ]]; then
  echo "    using cached RPMs in ${CACHE}"
else
  DNF=(dnf download --destdir="${CACHE}" -y --nogpgcheck)
  if dnf repolist --enabled 2>/dev/null | grep -qE '^fedora[^ ]*'; then
    DNF+=( --repo=fedora )
  fi
  if dnf repolist --enabled 2>/dev/null | grep -qE '^updates[^ ]*'; then
    DNF+=( --repo=updates )
  fi

  if ! "${DNF[@]}" "${PKGS[@]}" 2>"${TOOL_ROOT}/dnf-download.log"; then
    echo "WARN: constrained download failed; retrying default repos" >&2
    dnf download --destdir="${CACHE}" -y --nogpgcheck "${PKGS[@]}" \
      2>>"${TOOL_ROOT}/dnf-download.log" || {
      echo "ERROR: dnf download failed; see ${TOOL_ROOT}/dnf-download.log" >&2
      exit 1
    }
  fi
fi

# Prefer x86_64 packages when both arches downloaded
shopt -s nullglob
for rpm in "${CACHE}"/*.rpm; do
  base="$(basename "${rpm}")"
  case "${base}" in
    *.i686.rpm)
      twin="${base/.i686.rpm/.x86_64.rpm}"
      if [[ -f "${CACHE}/${twin}" ]]; then
        continue
      fi
      ;;
  esac
  dest="${EXTRACT}/$(basename "${rpm}" .rpm)"
  if [[ ! -d "${dest}/usr" ]]; then
    mkdir -p "${dest}"
    (cd "${dest}" && rpm2cpio "${rpm}" | cpio -idmu --quiet)
  fi
done

# Assemble lib + bin search paths
LIB_PATHS=()
BIN_PATHS=()
while IFS= read -r -d '' d; do
  [[ -d "${d}/usr/lib64" ]] && LIB_PATHS+=("${d}/usr/lib64")
  [[ -d "${d}/usr/lib" ]] && LIB_PATHS+=("${d}/usr/lib")
  [[ -d "${d}/usr/bin" ]] && BIN_PATHS+=("${d}/usr/bin")
  [[ -d "${d}/usr/lib/rpm" ]] && echo "${d}/usr/lib/rpm" >"${TOOL_ROOT}/rpmconfigdir"
done < <(find "${EXTRACT}" -mindepth 1 -maxdepth 1 -type d -print0)

{
  echo "# Generated by bootstrap-update-test-tools.sh"
  echo "export NOVA_UPDATE_TEST_TOOLS=\"${TOOL_ROOT}\""
  echo "export LD_LIBRARY_PATH=\"$(IFS=:; echo "${LIB_PATHS[*]}"):\${LD_LIBRARY_PATH:-}\""
  echo "export PATH=\"$(IFS=:; echo "${BIN_PATHS[*]}"):\${PATH}\""
  if [[ -f "${TOOL_ROOT}/rpmconfigdir" ]]; then
    echo "export NOVA_RPMCONFIGDIR=\"$(cat "${TOOL_ROOT}/rpmconfigdir")\""
  fi
} >"${TOOL_ROOT}/env.sh"

# shellcheck disable=SC1091
source "${TOOL_ROOT}/env.sh"

command -v rpmbuild >/dev/null || { echo "ERROR: rpmbuild not available after bootstrap" >&2; exit 1; }
command -v createrepo_c >/dev/null || { echo "ERROR: createrepo_c not available after bootstrap" >&2; exit 1; }

echo "    rpmbuild=$(command -v rpmbuild) ($(rpmbuild --version | head -1))"
echo "    createrepo_c=$(command -v createrepo_c) ($(createrepo_c --version | head -1))"
echo "PASS — update-test tools ready"
