# SPDX-FileCopyrightText: Nova
# SPDX-License-Identifier: MIT
---
efiBootLoader: "sb-shim"
grubInstall: "grub2-install"
grubMkconfig: "grub2-mkconfig"
grubCfg: "/boot/grub2/grub.cfg"
grubProbe: "grub2-probe"
efiBootMgr: "efibootmgr"
efiBootloaderId: "NovaOS"
installEFIFallback: true
