# SPDX-FileCopyrightText: Nova
# SPDX-License-Identifier: MIT
---
displaymanagers:
  - sddm

defaultDesktopEnvironment:
    executable: "/usr/local/libexec/novaos-plasma-x11"
    desktopFile: "novaos-plasma.desktop"

basicSetup: false
sysconfigSetup: false

sddm:
  configuration_file: "/etc/sddm.conf.d/zz-novaos-installed.conf"
