# SPDX-FileCopyrightText: Nova
# SPDX-License-Identifier: MIT
---
units:
  - name: "NetworkManager.service"
    action: "enable"
    mandatory: true
  - name: "sddm.service"
    action: "enable"
    mandatory: true
  - name: "nova-updated.socket"
    action: "enable"
    mandatory: true
  - name: "nova-updated.service"
    action: "enable"
    mandatory: true
  - name: "graphical.target"
    action: "enable"
    mandatory: true
  - name: "novaos-desktop-verify.service"
    action: "disable"
    mandatory: false
  - name: "novaos-desktop-verify.service"
    action: "mask"
    mandatory: false
