# SPDX-FileCopyrightText: Nova
# SPDX-License-Identifier: MIT
---
dontChroot: false
timeout: 120
verbose: true

script:
  - command: "/usr/sbin/novaos-post-install.sh"
    timeout: 120
    verbose: true

i18n:
  name: "NovaOS post-install hardening"
  name[it]: "Hardening post-installazione NovaOS"
