[General]
showlogo=shown
showClock=true
logo=/usr/share/pixmaps/novaos.png
type=image
color=#0f2744
fontSize=10
background=/usr/share/wallpapers/NovaOS/contents/images/3840x2160.png
needsFullUserModel=false
